POST http://localhost:8080/generate
Content-Type: application/json

{
    "objectives": [
        {
            "name": "Cost",
            "type": "double",
            "process": {
                "incrementWith": "Cost"
            },
            "maximize": false,
            "calculate": {
                "expression": "sum / Cost"
            }
        },
        {
            "name": "Importance",
            "type": "double",
            "maximize": false,
            "process": {
                "incrementWith": "Importance"
            },
            "calculate": {
                "invert": "true",
                "expression": "sum / Importance"
            }
        },
        {
            "name": "Profit",
            "type": "double",
            "maximize": false,
            "process": {
                "incrementWith": "Profit"
            },
            "calculate": {
                "invert": "true",
                "expression": "sum / Profit"
            }
        },
        {
            "name": "Size",
            "type": "int",
            "maximize": false,
            "process": {
                "incrementWith": 1
            },
            "calculate": {
                "expression": "sum / Solution",
                "invert": "true"
            }
        }
    ],
    "item": {
        "name": "Task",
        "objectives": [
            "Cost",
            "Profit",
            "Importance"
        ]
    },
    "solution": {
        "name": "Requirement"
    }
}
